load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "jrello",
    url = "https://github.com/GuyMograbi/jrello/archive/refs/heads/master.tar.gz",
    # strip_prefix = "my_library-1.0.0",
    build_file = "//:jrello.BUILD",
)